version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pos-kyd-backend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    container_name: pos-kyd-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos_kyd_db
    volumes:
      - posdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  posdata_dev:
